name: cd

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: ./scripts/buildprod.sh

      - name: Add binary to artifact
        uses: actions/upload-artifact@v2
        with:
          name: container-viewer-${{ github.ref_name }}