name: cd

on:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: ./scripts/buildprod.sh

      - name: Add binary to artifact
        uses: actions/upload-artifact@v2
        with:
          name: container-viewer-${{ github.ref_name }}
          path: build/

      - name: Upload the binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          file: build/*
          file_glob: true